# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'


  # Comment the next line if you don't want to use dynamic frameworks


target 'memoapp' do
  use_frameworks!
pod 'JTAppleCalendar'
end

